ALTER TYPE "EstadoPedido" ADD VALUE IF NOT EXISTS 'EN_PROCESO';
ALTER TYPE "EstadoPedido" ADD VALUE IF NOT EXISTS 'TERMINADA';
ALTER TYPE "EstadoPedido" ADD VALUE IF NOT EXISTS 'RECHAZADA';

ALTER TABLE "usuarios" ALTER COLUMN "password" DROP NOT NULL;
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "telefono" TEXT;
ALTER TABLE "usuarios" ADD COLUMN IF NOT EXISTS "googleId" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "usuarios_googleId_key" ON "usuarios"("googleId");

ALTER TABLE "pedidos" ADD COLUMN IF NOT EXISTS "numeroContacto" TEXT;
